Namespace Cryptography

	''' <summary>Enum Representing Cryptographic Hash Algorithm</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>01/02/2014 12:15:58</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Hermes_\_Cryptography\Enums\HashType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Hermes_\_Cryptography\Enums\HashType.tt", "1")> _
	Public Enum HashType As System.Int32

		''' <summary>MD5 Algorithm</summary>
		MD5 = 1

		''' <summary>FNV Algorithm</summary>
		FNV_MOD = 2

		''' <summary>SHA-1 Algorithm</summary>
		SHA1 = 3

		''' <summary>SHA-256 Algorithm</summary>
		SHA256 = 4

		''' <summary>SHA-384 Algorithm</summary>
		SHA384 = 5

		''' <summary>SHA-512 Algorithm</summary>
		SHA512 = 6

	End Enum

End Namespace