Namespace Files

	''' <summary>Enum Representing Sort Types</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>01/02/2014 12:16:41</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Hermes_\_Files\Enums\SortType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Hermes_\_Files\Enums\SortType.tt", "1")> _
	Public Enum SortType As System.Int32

		''' <summary>Descending Sort Based on Last Modified Date.</summary>
		Last_Modified = 0

		''' <summary>Ascending Sort Based on Name.</summary>
		By_Name = 1

		''' <summary>Descending Sort Based on Name.</summary>
		By_Name_Desc = 2

	End Enum

End Namespace