Namespace Email

	''' <summary>Enum Representing Email Body Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>01/02/2014 12:15:59</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Hermes_\_Email\Enums\BodyType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Hermes_\_Email\Enums\BodyType.tt", "1")> _
	Public Enum BodyType As System.Int32

		''' <summary>Text</summary>
		Text = 0

		''' <summary>HTML</summary>
		HTML = 1

	End Enum

End Namespace