Namespace Email

	''' <summary>Enum Representing Email Header Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>01/02/2014 12:15:59</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Hermes_\_Email\Enums\HeaderType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Hermes_\_Email\Enums\HeaderType.tt", "1")> _
	Public Enum HeaderType As System.Int32

		''' <summary>Meta_Name</summary>
		Meta_Name = 0

		''' <summary>Meta_HTTP_Equiv</summary>
		Meta_HTTP_Equiv = 1

		''' <summary>Base</summary>
		Base = 2

		''' <summary>StylesheetLink</summary>
		StylesheetLink = 3

		''' <summary>ScriptLink</summary>
		ScriptLink = 4

		''' <summary>Script</summary>
		Script = 5

		''' <summary>Style</summary>
		Style = 6

		''' <summary>Title</summary>
		Title = 7

	End Enum

End Namespace