Namespace Email

	''' <summary>Enum Representing Sending Type</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>01/02/2014 12:16:00</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Hermes_\_Email\Enums\SendingType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Hermes_\_Email\Enums\SendingType.tt", "1")> _
	Public Enum SendingType As System.Int32

		''' <summary>Blind_Carbon_Copy</summary>
		Blind_Carbon_Copy = 0

		''' <summary>Single_Recipient</summary>
		Single_Recipient = 1

	End Enum

End Namespace