Namespace Authentication

	''' <summary>Enum Representing JWT Hash Algorithms</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>01/02/2014 12:14:35</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Hermes_\_Authentication\Enums\JwtHashAlgorithm.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Hermes_\_Authentication\Enums\JwtHashAlgorithm.tt", "1")> _
	Public Enum JwtHashAlgorithm As System.Int32

		''' <summary>HS256</summary>
		HS256 = 1

		''' <summary>HS384</summary>
		HS384 = 2

		''' <summary>HS512</summary>
		HS512 = 3

	End Enum

End Namespace