Namespace Web

	''' <summary>Enum Representing Comparative Operator </summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>01/02/2014 12:17:58</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Hermes_\_Web\Enums\ComparativeOperator.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Hermes_\_Web\Enums\ComparativeOperator.tt", "1")> _
	Public Enum ComparativeOperator As System.Int32

		''' <summary>None</summary>
		None = 0

		''' <summary>Equals</summary>
		Equals = 1

		''' <summary>Greater_Than</summary>
		Greater_Than = 2

		''' <summary>Less_Than</summary>
		Less_Than = 3

		''' <summary>Greater_Than_Or_Equals</summary>
		Greater_Than_Or_Equals = 4

		''' <summary>Less_Than_Or_Equals</summary>
		Less_Than_Or_Equals = 5

	End Enum

End Namespace